### PR TITLE
Upgrade for Marionette v3 [Breaking Changes]

### PR DESCRIPTION
**Pull request by joshlasdin**
I realize this project is generally dormant, but recently wanted to upgrade Marionette in a project which was using this. Marionette v3 removes `LayoutView` and `ItemView` in favor of the newly merged `View`. I've refactored the mixin to apply to the new `View` and kept support for `CompositeView`, despite it being marked for deprecation in the next major release of Marionette. I also updated the test suite to run against the current view specs  from the Marionette repo.

I was unable to update the samples or perf.

### CODE REVIEW

**Comment by tiagorg** [comment]
Hi @joshlasdin, wow thanks for such detailed work! I will look it up. I noticed the Travis CI build failed which is unrelated with your changes, but related with some package/node version that changed from when I authored it back in the day -> https://travis-ci.org/tiagorg/marionette-vdom/builds/170561508

I will look it up tonight and I will also attempt to fix that build issue to ensure all the builds are fine. If I can't get that to happen I will then download your branch and run the tests locally, if they all pass it should be good to merge as is.

**Comment by joshlasdin** [comment]
@tiagorg Sounds great, thanks! I did run the test suite locally, so it _should_ pass. Guessing it's like you said, related to some package/node versioning.

**Comment by tiagorg** [comment]
I did a manual merge and I added a commit to upgrade the node version on Travis. Now the build looks good: https://travis-ci.org/tiagorg/marionette-vdom/builds/170657194

I have also just bumped the version to v0.2.0 with this improvement and I've just published it to NPM: https://www.npmjs.com/package/marionette-vdom

Next I will add some documentation to state that from v0.2 onwards there is support to Marionette 3, and Marionette 2 users should stick to v0.1

Thanks again @joshlasdin for your great effort!! :) I hope this lib is being useful to you

**Comment by tiagorg** [comment]
I have just released v0.2.1 with updated samples (demo, perf), updated documentation and reduced minified bundle by using uglifyjs dead code removal!

**Comment by joshlasdin** [comment]
@tiagorg Awesome, thank you!!

**Comment by joshlasdin** [comment]
@tiagorg just noticed -- npm seems to only have `0.2.0` and not `0.2.1`

**Comment by joshlasdin** [comment]
@tiagorg sorry, one more thing: looks like you broke the package in ed8f22cd5d3526de99c573b40d22c7bba2afe2ff by moving `index.js` to `src/index.js` but not updating the `main` property in the `package.json`

**Comment by joshlasdin** [comment]
Should just be able to set `"main": "src/index.js"` and publish to `0.2.2`

**Comment by tiagorg** [comment]
Oh crap! That's what happens when you are eager to push your code because it's late and your dog is staring at you and crying because he wants to go out 😆 

Are you completely blocked right now? Because I'm at work and I am not sure if I can get this done immediately but surely can do it later on today. Anyway I will give it a try

**Comment by tiagorg** [comment]
I haven't noticed you had already given me everything I needed! Thanks for that. It's done!

https://www.npmjs.com/package/marionette-vdom

Can you please check it to see if it went thru well this time?

Later on I'll update the changelogs

**Comment by joshlasdin** [comment]
Looks like that update (`0.2.2`) is working great, thanks @tiagorg!

**Pull request merged**
