### PR TITLE
Browser version

### PR DESCRIPTION
**Pull request by samccone**
ok @tiagorg went ahead and put together a ready to go browser version and made a nice sample app for everyone to use .. just using plain ol bower and nothing fancy.

After this lands we should chat about how to actually get this out there and how to distribute. 

:dancer: 

via #6 

---------

PS thanks for everyone's great work on this, and thanks for pestering me to get this out. This is going to be a huge win for so many apps, removing the complexity of worrying what state your DOM is in and simply being able to call render.

:dancer:

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/tiagorg/marionette-vdom/pull/10" target="_blank">ReviewNinja

**Comment by tiagorg** [comment]
That is fantastic, @samccone ! Thanks very much! I will release a new version on npm right now :)

In order to distribute it for the browser, what would you suggest? Bower, jspm?

**Comment by tiagorg** [comment]
hey @samccone - I have a question about the browser version.

maybe I didnt get it right, but if the browser version is what gets created on the "dist" folder, that is actually wrapping up all the dependencies altogether, which sums to 615 KB.

I wonder if is there a way to only include the marionette-vdom module as a standalone plugin to be loaded after marionette.js - or if that is not a good practice then what would be a good way to distribute it to browsers.

**Comment by samccone** [comment]
> maybe I didnt get it right, but if the browser version is what gets created on the "dist" folder, that is actually wrapping up all the dependencies altogether, which sums to 615 KB.

I only include the VDOM helper libs, since they are not easy to get via bower and whatnot, the build i am making is one for people who have underscore, jquery, backbone, marionette already on the page and want to use your view class right now.

For someone that wants to use this tool with something like browserify, or amd, or require they should not use this dist, I can make another one that excludes everything except for your work.

also, since dist is ignored from the repo, before publishing to npm we will want to run the build file and then run npm publish.

If you are around tonight just ping me and I can show you how to do all of this :)

**Comment by tiagorg** [comment]
gotcha! it makes all the sense.

sure thing, I will ping you once I get home. thanks again!

**Comment by tiagorg** [comment]
Hey @samccone - if you are available sometime tomorrow please let me know.

BTW I have been looking into the bundle and I found that one of my dependencies was including lodash. I just updated my dependency for a new version which no longer includes lodash, and so the bundle got smaller, for the cost of nor supporting IE8- anymore. Which should be fine.

The bundle is now 395 KB unminified / 250 KB minified.

**Comment by samccone** [comment]
:+1: :+1:

**Pull request merged**
